name       : dracut
version    : '045'
release    : 37
source     :
    - https://www.kernel.org/pub/linux/utils/boot/dracut/dracut-045.tar.xz : ca9c7ea54d3efc8b57ac1427cc5fa4d66688f6cf9d3088f4c5e7ae7c7e84ebf8
homepage   : http://dracut.wiki.kernel.org/index.php/Main_Page
license    :
    - GPL-2.0
summary    : initramfs system
component  : system.boot
description: |
    dracut is an event driven initramfs infrastructure. dracut (the tool) is used to create an initramfs image by copying tools and files from an installed system and combining it with the dracut framework
builddeps  :
    - pkgconfig(libkmod)
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-stateless-glibc-ldconfig-configuration.patch
    %configure
build      : |
    %make
install    : |
    %make_install
    # unsupported on Solus
    rm -rf $installdir/%libdir%/dracut/modules.d/00dash
