name       : dracut
version    : '046'
release    : 39
source     :
    - https://www.kernel.org/pub/linux/utils/boot/dracut/dracut-046.tar.xz : 3cb206abc198811972d452d53e88c32f29dd1b0bb24e35e23b4056aa74824f99
homepage   : http://dracut.wiki.kernel.org/index.php/Main_Page
license    :
    - GPL-2.0
summary    : initramfs system
component  : system.boot
description: |
    dracut is an event driven initramfs infrastructure. dracut (the tool) is used to create an initramfs image by copying tools and files from an installed system and combining it with the dracut framework
builddeps  :
    - pkgconfig(libkmod)
rundeps    :
    - bash-recovery
setup      : |
    %apply_patches
    %configure
build      : |
    %make
install    : |
    %make_install
    # unsupported on Solus
    rm -rf $installdir/%libdir%/dracut/modules.d/00dash
